name: "CUPS printserver"
version: "0.16"
slug: "cups"
description: "The standards-based, open source printing system"
arch:
  - amd64
  - armhf
  - armv7 
  - aarch64
  - i386
ports:
  631/tcp: 631
ports_description:
  631/tcp: "CUPS Web interface"
options:
  user: "admin"
  passwd: "pass"
schema:
  user: "str"
  passwd: "password"
init: false
host_network: true

